--Group table
CREATE TABLE "group"
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    varchar(255) not null,
    details varchar(255)

);

create sequence group_sequence start with 1 increment by 1;

insert into "group" (name, details)
VALUES ('CodeCrafters', 'Group of coding enthusiasts learning together at bootcamp'),
       ('DataExplorers', 'Data analysis and visualization group attending data science bootcamp'),
       ('WebWarriors', 'Web development group honing their skills in a bootcamp environment');

--Person group relation table
CREATE TABLE person_group
(
    pid      bigint REFERENCES PERSON (pid),
    group_id BIGINT REFERENCES "group" (id)
);

insert into person_group (pid, group_id)
values (39001234567, 1),
       (49001123456, 2),
       (69002234567, 2),
       (49002345678, 3),
       (59003456789, 3);