--Task table
CREATE TABLE task
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    short_desc varchar(255) not null,
    details    text,
    start_date TIMESTAMP    not null,
    end_date   TIMESTAMP,
    group_id   BIGINT,
    FOREIGN KEY (group_id) REFERENCES "group" (id)
);

create sequence task_sequence start with 2 increment by 1;


INSERT INTO task (short_desc, details, start_date, end_date, group_id)
VALUES ('Complete HTML/CSS exercises', 'Finish exercises 1-5 in the HTML/CSS module', '2024-03-20 09:00:00',
        '2024-03-20 18:00:00', 1),
       ('Implement CRUD operations', 'Develop CRUD functionality for the project', '2024-03-21 10:00:00',
        '2024-03-22 18:00:00', 2),
       ('Create data visualization dashboard', 'Design and implement a dashboard for data visualization',
        '2024-03-23 09:00:00', '2024-03-25 18:00:00', 3),
       ('Deploy web application to AWS', 'Deploy the web application to Amazon Web Services', '2024-03-26 09:00:00',
        '2024-03-26 18:00:00', 1),
       ('Automate testing procedures', 'Write automated tests for the application', '2024-03-27 10:00:00',
        '2024-03-28 18:00:00', 2);